//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rab
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDK0701_Polzovyateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MDK0701_Polzovyateli()
        {
            this.MDK0701_Vidacha = new HashSet<MDK0701_Vidacha>();
        }
    
        public int id_polzovyatelya { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Rol { get; set; }
        public string Login { get; set; }
        public string Parol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDK0701_Vidacha> MDK0701_Vidacha { get; set; }
    }
}
