//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rab
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDK0701_Knigi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MDK0701_Knigi()
        {
            this.MDK0701_Vidacha = new HashSet<MDK0701_Vidacha>();
        }
    
        public int id_knigi { get; set; }
        public string Nazvanie { get; set; }
        public string Avtor { get; set; }
        public string God_izdaniya { get; set; }
        public string Kolichestvo_na_sklade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDK0701_Vidacha> MDK0701_Vidacha { get; set; }
    }
}
