//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rab
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDK0701_Vidacha
    {
        public int id_vidachi { get; set; }
        public Nullable<int> id_knigi { get; set; }
        public Nullable<int> id_polzovyatelya { get; set; }
        public string data_vidachi { get; set; }
        public string data_sdachi { get; set; }
    
        public virtual MDK0701_Knigi MDK0701_Knigi { get; set; }
        public virtual MDK0701_Polzovyateli MDK0701_Polzovyateli { get; set; }
    }
}
