//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user59_dbEntities : DbContext
    {
        public user59_dbEntities()
            : base("name=user59_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MDK0701_Knigi> MDK0701_Knigi { get; set; }
        public virtual DbSet<MDK0701_Polzovyateli> MDK0701_Polzovyateli { get; set; }
        public virtual DbSet<MDK0701_Vidacha> MDK0701_Vidacha { get; set; }
    }
}
